version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
    healthcheck: # O healtcheck é uma funcionalidade do docker que verifica se o container está saudável
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 3s
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d/
      # - ./db_data:/var/lib/postgresql/data # essa linha persiste o DB localmente
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=fatec
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy # Apesar de funcionar aqui, é costumário colocar dependencias mais estritas
